apiVersion: v1
kind: Service
metadata:
  name: qr-menu
  labels:
    app: qr-menu
spec:
  selector:
    app: qr-menu
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer
